### PR TITLE
Update to using the latest aw-client

### PR DESCRIPTION
**Pull request by devzsolt**
This changeset contains several small changes:
- update submodules aw-client-js and media to latest
- fix the extension to work with the latest aw-client:
  - AppEditorActivityHeartbeat --> AppEditorEvent
  - createBucket --> ensureBucket
  - options object in AWClient constructor
  - timestamp should be a Date not a string
- fix lint error in catch of _sendHeartbeat
- restore _getProjectName() to populate field `projectName` (I liked the previous logic better so restored it into a new field keeping `project` intact logging the project path)
- also includes my previous PR #5

### CODE REVIEW

**Comment by Otto-AA** [comment]
Thanks for your contribution, it seems fine to me :+1: 
I haven't installed activitywatch since my last computer reset, so I can't test it, but from the logic it seems nice.

Regarding merging and publishing via vsce, I guess it would be better if someone else becomes the maintainer of this watcher. I myself sadly don't have time for maintaining, testing new pull requests, finding bugs, etc. anymore, so I would suggest to find a new maintainer or mark it as unmaintained.
@johan-bjareholt 

And here is the discussion about the format if you want to read it: https://forum.activitywatch.net/t/bucket-and-event-design-fo-vs-code-extension/120/9

**Comment by johan-bjareholt** [comment]
@Otto-AA Yes that is still my mail, that'll work fine.

Also, I tested the code and everything seems to work fine

**Comment by johan-bjareholt** [comment]
I'll merge this, fix the comment I made and add it to the ChangeLog because I'm likely not going to have time to review this later in the week.

**Comment by johan-bjareholt** [comment]
@devzsolt Thanks for the PR by the way! :-)

**Comment by devzsolt** [comment]
@johan-bjareholt @Otto-AA you're welcome. Sorry that I didn't follow the conversation. I'm glad that you have found my PRs useful. I'm using it for almost a week now and works well. Thank you for developing this extension in the first place!

Thanks for explaining why you discarded the project name idea. I'm not sure yet if I'll ever use it but in the future I'm thinking about some pattern based categorization and a simplified custom visualization. Of course the full path is unique for pattern matching and possibly the patterns would have a metadata containing the project name (which I would enter once manually)... so you're right, it's possibly useless data :)

**Comment by ErikBjare** [comment]
@devzsolt If you're interested in categorizing activity using pattern-matching, check out my work in aw-research here: https://github.com/ActivityWatch/aw-research/pull/12

And the general issue on the matter: https://github.com/ActivityWatch/activitywatch/issues/95

**Pull request merged**
