### PR TITLE
Send Git branch name.

### LINKED ISSUE #22: Feature request: Send source control branch name along with the project name
Often times I work on a single project with different branches, it would be really convenient if the extension can track how much time i spent on each branch say.

`master` -> 10m
`bugfix123` -> 20m
`GH-112-fix-templates` -> 30m

Note that usually the branch name has a prefix with an issue key from jira, github etc so it's really convenient for tracking how much time was spent on some issue (the editing part atleast).

### PR DESCRIPTION
**Pull request by michbart**
This pull request adds support for sending Git branch name along with other data. It uses VS Code [integrated Git API]( https://github.com/microsoft/vscode/tree/main/extensions/git).
Closes #22.

### CODE REVIEW

**Comment by iloveitaly** [comment]
@michbart curious why this was helpful to send over for you? What are you using this for?

**Comment by michbart** [comment]
It is a convention in our company to start branch name with Redmine issue ID, such as `rm12345-xxx`. This PR would help to analyze, what issue the user was working on at given time and how much time he had spend. Of course this is the case just for VS Code, but it can help at least a bit to reconstruct given day.

**Comment by iloveitaly** [comment]
Ah, makes sense! This could be helpful to determine how much time people are spending on bugs vs features. @ErikBjare what do you think about merging this in?

**Comment by GeorchW** [comment]
This would be really sweet! @johan-bjareholt @ErikBjare ?

**Comment by ErikBjare** [comment]
Thanks for the ping @GeorchW, merged!

Sorry for the late response. Will get around to cutting a new release soon.

**Comment by lightheaded** [comment]
Thanks a lot for this! I was looking for a VSCode time tracker specifically tracking branch names, as I'd like to know what I was working on weeek-by-week, and we also use Jira ticket numbers in our branch names, so it makes it a very powerful analysis tool.

However, after installing the extension from VS Marketplace, I see no branch data being sent:
image

It seems that because this PR was merged without bumping the extension version, the Marketplace is still providing an old version. Here's the extension code that was installed locally where it can be seen that it doesn't include the code introduced by this PR:
image

**Pull request merged**
